enabling test run in circle ci - added microsoft edge

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -45,10 +45,15 @@ jobs:
             curl -sS -o chromedriver.zip https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
             sudo unzip chromedriver.zip -d /usr/local/bin/
             rm chromedriver.zip
-            curl -sS -o microsoft-edge-stable.deb https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_109.0.1518.78-1_amd64.deb
-            sudo dpkg -i microsoft-edge-stable.deb
-            sudo apt-get install -f
-            rm microsoft-edge-stable.deb
+            for i in {1..5}; do curl -sS -o microsoft-edge-stable.deb https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_109.0.1518.78-1_amd64.deb && break || sleep 5; done
+            if [ -f microsoft-edge-stable.deb ]; then
+              sudo dpkg -i microsoft-edge-stable.deb
+              sudo apt-get install -f
+              rm microsoft-edge-stable.deb
+            else
+              echo "Failed to download microsoft-edge-stable.deb"
+              exit 1
+            fi
             curl -sS -o edgedriver.zip https://msedgedriver.azureedge.net/109.0.1518.78/edgedriver_linux64.zip
             sudo unzip edgedriver.zip -d /usr/local/bin/
             rm edgedriver.zip
